return {
  -- 'yetone/avante.nvim',
  -- event = 'VeryLazy',
  -- version = false, -- Set this to "*" to always pull the latest release version, or set it to false to update to the latest code changes.
  -- opts = {
  --   provider = 'openrouter',
  --   providers = {
  --     openrouter = {
  --       __inherited_from = 'openai',
  --       api_key_name = 'OPENROUTER_API_KEY',
  --       endpoint = 'https://openrouter.ai/api/v1',
  --       model = 'mistralai/devstral-small:free',
  --     },
  --     nvidia = {
  --       __inherited_from = 'openai',
  --       api_key_name = 'NVIDIA_API_KEY',
  --       endpoint = 'https://integrate.api.nvidia.com/v1',
  --       model = 'bigcode/starcoder2-15b',
  --       -- timeout = 30000, -- Timeout in milliseconds
  --       extra_request_body = {
  --         temperature = 0.6,
  --         max_tokens = 512,
  --         -- stream = true,
  --         top_p = 0.85,
  --       },
  --     },
  --     mistral = {
  --       __inherited_from = 'openai',
  --       api_key_name = 'CODESTRAL_API_KEY',
  --       endpoint = 'https://codestral.mistral.ai/v1/chat/completions',
  --       model = 'open-codestral-mamba',
  --       extra_request_body = {
  --         max_tokens = 1024,
  --       },
  --     },
  --   },
  -- },
  -- -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  -- build = 'make',
  -- -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  -- dependencies = {
  --   'nvim-treesitter/nvim-treesitter',
  --   'nvim-lua/plenary.nvim',
  --   'MunifTanjim/nui.nvim',
  --   --- The below dependencies are optional,
  --   'nvim-telescope/telescope.nvim', -- for file_selector provider telescope
  --   -- 'stevearc/dressing.nvim', -- for input provider dressing
  --   'nvim-tree/nvim-web-devicons', -- or echasnovski/mini.icons
  --   {
  --     -- Make sure to set this up properly if you have lazy=true
  --     'MeanderingProgrammer/render-markdown.nvim',
  --     opts = {
  --       file_types = { 'markdown', 'Avante' },
  --     },
  --     ft = { 'markdown', 'Avante' },
  --   },
  -- },
}
